/**
 * The committed history bundle (generated by the production pipeline) must agree, week by week,
 * with grades from an independent Python implementation working straight from ESPN JSON.
 */

import { describe, expect, it } from 'vitest';
import oracleJson from '../fixtures/history/oracle-2021-2025.json';
import { HISTORY_BUNDLE } from '../src/server/historyBundle';
import { recordStats, scopeWeeks } from '../src/shared/historyStats';

interface OracleWeek {
  season: number;
  week: number;
  games: number;
  legs: number;
  hit: number;
  busted: string[];
}

const oracle = Object.values(oracleJson as Record<string, OracleWeek>);
const seasons = Object.values(HISTORY_BUNDLE);

describe('history bundle', () => {
  it('contains 2021–2025, each complete with 18 weeks in order', () => {
    expect(Object.keys(HISTORY_BUNDLE).map(Number)).toEqual([2021, 2022, 2023, 2024, 2025]);
    for (const s of seasons) {
      expect(s.complete).toBe(true);
      expect(s.weeks.map((w) => w.week)).toEqual(Array.from({ length: 18 }, (_, i) => i + 1));
    }
  });

  it('covers every oracle week', () => {
    expect(oracle).toHaveLength(90);
  });

  it.each(oracle.map((o) => [o.season, o.week, o] as const))('%i week %i matches the independent grader', (season, week, o) => {
    const grade = HISTORY_BUNDLE[season]?.weeks.find((w) => w.week === week);
    expect(grade).toBeDefined();
    expect({
      status: grade?.status,
      games: grade?.games,
      voidGames: grade?.voidGames,
      totalLegs: grade?.totalLegs,
      hitLegs: grade?.hitLegs,
      missed: grade?.missedLegs.map((l) => `${l.abbr} ${l.type}`).sort(),
    }).toEqual({
      status: o.hit === o.legs ? 'won' : 'lost',
      games: o.games,
      voidGames: 0,
      totalLegs: o.legs,
      hitLegs: o.hit,
      missed: [...o.busted].sort(),
    });
  });

  it('adds up to 3–87 with wins in 2022 W12, 2022 W16 and 2024 W18', () => {
    expect(recordStats(scopeWeeks(seasons, 'all'))).toMatchObject({ wins: 3, losses: 87, graded: 90 });
    const won = scopeWeeks(seasons, 'all')
      .filter((w) => w.status === 'won')
      .map((w) => `${w.season} W${w.week}`);
    expect(won).toEqual(['2022 W12', '2022 W16', '2024 W18']);
  });

  it('flags 2022 week 16 (1 game) as the only short slate', () => {
    const short = scopeWeeks(seasons, 'all').filter((w) => w.shortSlate);
    expect(short.map((w) => [w.season, w.week, w.games])).toEqual([[2022, 16, 1]]);
  });

  it('dates every week on a Sunday', () => {
    for (const w of scopeWeeks(seasons, 'all')) {
      expect(w.slateDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(new Date(`${w.slateDate}T12:00:00Z`).getUTCDay()).toBe(0);
    }
  });
});
