/**
 * Completed seasons shipped with the app, generated by `npm run build:history` (ARCHITECTURE ADR-006).
 * When a season ends, generate its file and add it here; until then it's graded at runtime.
 */

import type { SeasonHistory } from '../../shared/history';
import season2021 from './seasons/2021.json';
import season2022 from './seasons/2022.json';
import season2023 from './seasons/2023.json';
import season2024 from './seasons/2024.json';
import season2025 from './seasons/2025.json';

export const HISTORY_BUNDLE: Record<number, SeasonHistory> = Object.fromEntries(
  [season2021, season2022, season2023, season2024, season2025].map((s) => [s.season, s as unknown as SeasonHistory]),
);
